### ISSUE TITLE
Blog Posts: No alt-text or title-text attributes on featured images

### ISSUE THREAD

**Issue by ProfYaffle** [xbmc/kodi-tv#56]
... although inline images have them. Looks like it might be add-able through config, though:

https://answers.netlify.com/t/alt-text-and-title-text-for-featured-image/1681/2

If that isn't possible, we should probably avoid featured images, and use leading inline images instead for accessibility reasons.

**Comment by pkscout** [comment]
It looks pretty straight forward to add the title and alt text to the image and the blog management GUI, so I'll plan on doing that. The only labor intensive part is going to be going back through 10 years of blog posts to add those. But if I do it in chucks of six months or a year, it won't be that bad.

**Comment by Razzeee** [comment]
I think if you show us how to do it, the team can make those edits. And you
can focus on improvements

**Comment by pkscout** [comment]
OK, the code and CMS updates are done so that a featured image can have both a title and alt text. I updated the Matrix final blog post so you can see what that looks like.  While you technically could update the alt text and title from the CMS GUI, I would not recommend it, as each time you save an updated post the entire site rebuilds.  Instead, I'd recommend getting a copy of the site via git and then editing the index.md file for each blog post in `src/content/article/`.  The title and alt text are in the frontmatter part at the top. An unedited file that has a featured image will look like this:

```
---
title: Refactoring of the Add-on Subsystem
date: 2021-01-03T00:52:00.000Z
author: Frank H.
featured_image:
  src: /images/blog/olav-ahrens-rotne-jvBXiynINGE-unsplash.jpg
  title: ''
  alt: ''
---
```

and a finished one will look like this:

```
---
title: Kodi 19.0 "Matrix" - Release
date: 2021-02-19T20:49:22.165Z
author: Prof Yaffle
featured_image:
  src: /images/blog/kodi_splash_v19.0_matrix_final_1080p.jpg
  title: Kodi 19 Matrix splash screen
  alt: Kodi 19 Matrix splash screen
---
```

We should probably figure out some process so that people aren't working on the same files at the same time. Not that we couldn't figure it out at merge, but I don't want to do double or triple work.
